export const PERMISSIONS = Object.freeze({
  ASSET_CREATE: 'asset:create',
  ASSET_READ: 'asset:read',
  ASSET_UPDATE: 'asset:update',
  ASSET_DELETE: 'asset:delete',
  FOLDER_READ: 'folder:read',
  FOLDER_MANAGE: 'folder:manage',
  USER_MANAGE: 'user:manage',
  TASK_MANAGE: 'task:manage',
  REVIEW_MANAGE: 'review:manage',
  TAG_MANAGE: 'tag:manage',
  ROLE_MANAGE: 'role:manage',
  SCRIPT_IDEA_READ: 'script-idea:read',
  SCRIPT_IDEA_MANAGE: 'script-idea:manage',
  ANALYTICS_VIEW: 'analytics:view',
  WORK_DIARY_MANAGE_SELF: 'work-diary:manage:self',
  WORK_DIARY_READ_ALL: 'work-diary:read:all',
  WORK_DIARY_READ_SELF: 'work-diary:read:self',
  WORK_DIARY_REVIEW: 'work-diary:review'
})
